parameters:
  - name: teamName
    type: string
  - name: envToDeploy
    default: development
    type: string
  - name: resource
    type: string
  - name: varPath
    type: string

variables:
  - template: pipelines/image-tags/common.yaml@EprAppConfigSettings
  - ${{ if eq(parameters.envToDeploy, 'development') }}:
      - template: ${{ parameters.varPath }}/${{ parameters.teamName }}-${{ parameters.envToDeploy }}.yaml@${{ parameters.resource }}
      - template: pipelines/image-tags/development.yaml@EprAppConfigSettings
      - template: pipelines/image-tags/${{ parameters.teamName }}-${{ parameters.envToDeploy }}.yaml@EprAppConfigSettings
      - name: env
        value: DEV1
  - ${{ elseif eq(parameters.envToDeploy, 'tst') }}:
      - template: ${{ parameters.varPath }}/${{ parameters.envToDeploy }}.yaml@${{ parameters.resource }}
      - template: pipelines/image-tags/${{ parameters.envToDeploy }}.yaml@EprAppConfigSettings
      - name: env
        value: TST1
  - ${{ elseif eq(parameters.envToDeploy, 'preprod') }}:
      - template: ${{ parameters.varPath }}/${{ parameters.envToDeploy }}.yaml@${{ parameters.resource }}
      - template: pipelines/image-tags/${{ parameters.envToDeploy }}.yaml@EprAppConfigSettings
      - name: env
        value: PRE1
  - ${{ elseif eq(parameters.envToDeploy, 'preprod2') }}:
      - template: ${{ parameters.varPath }}/${{ parameters.envToDeploy }}.yaml@${{ parameters.resource }}
      - template: pipelines/image-tags/${{ parameters.envToDeploy }}.yaml@EprAppConfigSettings
      - name: env
        value: PRE2
  - ${{ elseif eq(parameters.envToDeploy, 'prod') }}:
      - template: ${{ parameters.varPath }}/${{ parameters.envToDeploy }}.yaml@${{ parameters.resource }}
      - template: pipelines/image-tags/${{ parameters.envToDeploy }}.yaml@EprAppConfigSettings
      - name: env
        value: PRD1