
parameters:
- name: teamName
  type: string
- name: envToDeploy
  type: string
- name: webResourceGroupName
  type: string
- name: updateSettings
  type: boolean
- name: frontends
  type: object
  default:
  - repoName: FrontendObligationcheckerMicroservice
    varPath: vars/
    appService: DEVRWDWEBWAx401
  - repoName: FrontendAccountCreationMicroservice
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx402
  - repoName: EprLoggingApi
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx403
  - repoName: FrontendAccountManagementMicroservice
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx405
  - repoName: PackagingFrontend
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx410
  - repoName: RegulatorService
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx411
  - repoName: RegulatorAccountManagementMicroservice
    varPath: pipelines/vars-regulator/
    appService: DEVRWDWEBWAx412
  - repoName: CalculatorFrontend
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx421
  - repoName: PaymentFrontend
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx423
 
  
- name: functions
  type: object
  default:
  - repoName: EventDispatcherFunctionApp
    varPath: pipelines/vars/
    appService: DEVRWDWEBFAx401
  - repoName: PomFuncProducerValidation
    varPath: pipelines/vars/
    appService: DEVRWDWEBFAx402
  - repoName: PomSubmissionCheckSplitter
    varPath: pipelines/vars/
    appService: DEVRWDWEBFAx403
  - repoName: RegistrationValidationFunctionApp
    varPath: pipelines/vars/
    appService: DEVRWDWEBFAx404
  - repoName: AntiVirusFunctionApp
    varPath: pipelines/vars/
    appService: DEVRWDWEBFAx405
  - repoName: DocumentSchemaJobRunnerFunctionApp
    varPath: pipelines/vars/
    appService: DEVRWDWEBFAx406
  - repoName: BackendAccountMicroservice
    varPath: pipelines/vars/
    appService: DEVRWDWEBFAx407
  - repoName: SubsidiaryBulkUploadFunctionApp
    varPath: pipelines/vars/
    appService: DEVRWDWEBFAx408
  - repoName: PaymentMopUpFunctionApp
    varPath: pipelines/vars/
    appService: DEVRWDWEBFAx409
  - repoName: PRNObligationCalculationsFunctionApp
    varPath: pipelines/vars/
    appService: DEVRWDWEBFAx410
  - repoName: CalculatorServiceFunctionApp
    varPath: pipelines/vars/
    appService: DEVRWDWEBFAx411
  - repoName: PRNIntegrationFunctionApp
    varPath: pipelines/vars/
    appService: DEVRWDWEBFAx412
  

- name: facades
  type: object
  default:
  - repoName: FacadeAccountMicroservice
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx404
  - repoName: RegulatorServiceFacade
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx406
  - repoName: PomApiSubmissionStatus
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx408
  - repoName: PomApiWeb
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx409
  - repoName: RegulatorAccountFacade
    varPath: pipelines/vars-regulator/
    appService: DEVRWDWEBWAx413 
  - repoName: CommonDataAPi
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx415
  - repoName: PaymentFacade
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx424
    
- name: backendService
  type: object
  default:
  - repoName: BackendAccountMicroservice
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx407
    solutionFolder: src
    projectFolder: BackendAccountService.Api
    branchName: 'main-latest'

  - repoName: PRNCommonBackend
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx418
    solutionFolder: src
    projectFolder: EPR.PRN.Backend.API
    branchName: 'main-latest'

  - repoName: CalculatorAPI
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx422
    solutionFolder: src
    projectFolder: BackendAccountService.Api
    branchName: 'main-latest'

  - repoName: PaymentService
    varPath: pipelines/vars/
    appService: DEVRWDWEBWAx425
    solutionFolder: src
    projectFolder: BackendAccountService.Api
    branchName: 'main-latest'
  

stages:
- ${{ each service in parameters.functions }}:
  - stage: Deploy_${{ service.repoName }}_to_${{ service.appService }}
    ${{ if eq( parameters.updateSettings, 'true') }}:
      dependsOn: UpdateSettings
    ${{ else }}:
      dependsOn: []
    variables:
    - template: /vars/mass-deployment/app-deployment.yaml
      parameters:
        envToDeploy: ${{ parameters.envToDeploy }}
        resource: ${{ service.repoName }}
        varPath: ${{service.varPath}}
        teamName: ${{ parameters.teamName }}
    - name: imageTag
      value: $[variables.${{ service.appService }}]
    - ${{ if or( eq(parameters.envToDeploy, 'development'), eq(parameters.envToDeploy, 'DEV4') )}}:
      - name: targetEnvironment
        value: development
    - ${{ else }}:
      - name: targetEnvironment
        value: ${{ variables.env }}
    jobs:
    - template: epr-funcs-deployment-pipeline.yaml@CommonTemplates
      parameters:
        imageTag: $(imageTag)
        azureSubscription: ${{ variables.azureSubscription }}
        acrName: $(acr.azureContainerRegistryName)
        ${{ if eq(service.repoName, 'BackendAccountMicroservice') }}:
          registryName: $(validationApiRepository)
          serviceName: $(validationApiServiceName)
        ${{ else }}:
          registryName: $(acr.repositoryName)
          serviceName: ${{ variables.serviceName }}
        targetEnvironment: ${{ variables.targetEnvironment }}
    - template: templates/restart-service.yaml@CommonTemplates
      parameters:
        subscriptionName: ${{ variables.azureSubscription }}
        webResourceGroupName: ${{ parameters.webResourceGroupName }}
        ${{ if eq(service.repoName, 'BackendAccountMicroservice') }}:
          serviceName: $(validationApiServiceName)'
        ${{ else }}:
          serviceName: ${{ variables.serviceName }}
        targetEnvironment: ${{ variables.targetEnvironment }}
        
- ${{ each service in parameters.backendService }}:
  - stage: Deploy_${{ service.repoName }}_to_${{ service.appService }}
    ${{ if eq( parameters.updateSettings, 'true') }}:
      dependsOn: UpdateSettings
    ${{ else }}:
      dependsOn: []
  
    variables:
    - template: /vars/mass-deployment/app-deployment.yaml
      parameters:
        envToDeploy: ${{ parameters.envToDeploy }}
        resource: ${{ service.repoName }}
        varPath: ${{service.varPath}}
        teamName: ${{ parameters.teamName }}
    - name: imageTag
      value: $[variables.${{ service.appService }}]
    - ${{ if or( eq(parameters.envToDeploy, 'development'), eq(parameters.envToDeploy, 'DEV4') )}}:
      - name: targetEnvironment
        value: development
    - ${{ else }}:
      - name: targetEnvironment
        value: ${{ variables.env }}
    jobs:
    - template: epr-deployment-pipeline.yaml@CommonTemplates
      parameters:
        imageTag: $(imageTag)
        azureSubscription: ${{ variables.azureSubscription }}
        acrName: $(acr.azureContainerRegistryName)
        registryName: $(acr.repositoryName)
        serviceName: ${{ variables.serviceName }}
        targetEnvironment: ${{ variables.targetEnvironment }}
    - template: templates/restart-service.yaml@CommonTemplates
      parameters:
        subscriptionName: ${{ variables.azureSubscription }}
        webResourceGroupName: ${{ parameters.webResourceGroupName }}
        serviceName: ${{ variables.serviceName }}
        targetEnvironment: ${{ variables.targetEnvironment }}

    - job: databaseMigrations
      displayName: "Database Migration"
      steps:
        - template: templates/docker-run-sql-migration.yaml@CommonTemplates
          parameters:
            azureSubscription: ${{ variables.azureSubscription }}
            solutionFolder: ${{ service.solutionFolder }}
            projectFolder: ${{ service.projectFolder }}
            azureContainerRegistryName: $(acr.azureContainerRegistryName)
            repositoryName: $(acr.repositoryName)
            branchName: ${{ service.branchName }}

- ${{ each service in parameters.facades }}:
  - stage: Deploy_${{ service.repoName }}_to_${{ service.appService }}
    ${{ if eq( parameters.updateSettings, 'true') }}:
      dependsOn: UpdateSettings
    ${{ else }}:
      dependsOn: []
 

    variables:
    - template: /vars/mass-deployment/app-deployment.yaml
      parameters:
        envToDeploy: ${{ parameters.envToDeploy }}
        resource: ${{ service.repoName }}
        varPath: ${{service.varPath}}
        teamName: ${{ parameters.teamName }}
    - name: imageTag
      value: $[variables.${{ service.appService }}]
    - ${{ if or( eq(parameters.envToDeploy, 'development'), eq(parameters.envToDeploy, 'DEV4') )}}:
      - name: targetEnvironment
        value: development
    - ${{ else }}:
      - name: targetEnvironment
        value: ${{ variables.env }}
    jobs:
    - template: epr-deployment-pipeline.yaml@CommonTemplates
      parameters:
        imageTag: $(imageTag)
        azureSubscription: ${{ variables.azureSubscription }}
        acrName: $(acr.azureContainerRegistryName)
        registryName: $(acr.repositoryName)
        serviceName: ${{ variables.serviceName }}
        targetEnvironment: ${{ variables.targetEnvironment }}
    - template: templates/restart-service.yaml@CommonTemplates
      parameters:
        subscriptionName: ${{ variables.azureSubscription }}
        webResourceGroupName: ${{ parameters.webResourceGroupName }}
        serviceName: ${{ variables.serviceName }}
        targetEnvironment: ${{ variables.targetEnvironment }}

- ${{ each service in parameters.frontends }}:
  - stage: Deploy_${{ service.repoName }}_to_${{ service.appService }}
    ${{ if eq( parameters.updateSettings, 'true') }}:
      dependsOn: UpdateSettings
    ${{ else }}:
      dependsOn: []
 
    variables:
    - template: /vars/mass-deployment/app-deployment.yaml
      parameters:
        envToDeploy: ${{ parameters.envToDeploy }}
        resource: ${{ service.repoName }}
        varPath: ${{service.varPath}}
        teamName: ${{ parameters.teamName }}
    - name: imageTag
      value: $[variables.${{ service.appService }}]
    - ${{ if or( eq(parameters.envToDeploy, 'development'), eq(parameters.envToDeploy, 'DEV4') )}}:
      - name: targetEnvironment
        value: development
    - ${{ else }}:
      - name: targetEnvironment
        value: ${{ variables.env }}
    jobs:
    - template: epr-deployment-pipeline.yaml@CommonTemplates
      parameters:
        imageTag: $(imageTag)
        azureSubscription: ${{ variables.azureSubscription }}
        acrName: $(acr.azureContainerRegistryName)
        registryName: $(acr.repositoryName)
        serviceName: ${{ variables.serviceName }}
        targetEnvironment: ${{ variables.targetEnvironment }}
    - template: templates/restart-service.yaml@CommonTemplates
      parameters:
        subscriptionName: ${{ variables.azureSubscription }}
        webResourceGroupName: ${{ parameters.webResourceGroupName }}
        serviceName: ${{ variables.serviceName }}
        targetEnvironment: ${{ variables.targetEnvironment }}

